#! /bin/bash

g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c build_menu.cpp -o obj/Release/build_menu.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c help_menu.cpp -o obj/Release/help_menu.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c parserThread.cpp -o obj/Release/parserThread.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c projects.cpp -o obj/Release/projects.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rc_closeFileSavePrompt_dialog.cpp -o obj/Release/rc_closeFileSavePrompt_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rc_closeProjectSavePrompt_dialog.cpp -o obj/Release/rc_closeProjectSavePrompt_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rc_debugger_dialog.cpp -o obj/Release/rc_debugger_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rc_find_dialog.cpp -o obj/Release/rc_find_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rc_ideApp.cpp -o obj/Release/rc_ideApp.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rc_newFile_dialog.cpp -o obj/Release/rc_newFile_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit.cpp -o obj/Release/rcbasic_edit.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_fileProperties_dialog.cpp -o obj/Release/rcbasic_edit_fileProperties_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_frame.cpp -o obj/Release/rcbasic_edit_frame.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_gotoLine_dialog.cpp -o obj/Release/rcbasic_edit_gotoLine_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_newProject_dialog.cpp -o obj/Release/rcbasic_edit_newProject_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_preference_dialog.cpp -o obj/Release/rcbasic_edit_preference_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_projectEnvironment_dialog.cpp -o obj/Release/rcbasic_edit_projectEnvironment_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_projectSettings_dialog.cpp -o obj/Release/rcbasic_edit_projectSettings_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_projectVariableEdit_dialog.cpp -o obj/Release/rcbasic_edit_projectVariableEdit_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_replace_dialog.cpp -o obj/Release/rcbasic_edit_replace_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_searchWrap_dialog.cpp -o obj/Release/rcbasic_edit_searchWrap_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_edit_setColorScheme_dialog.cpp -o obj/Release/rcbasic_edit_setColorScheme_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_editrc_cancelDistProcess_dialog.cpp -o obj/Release/rcbasic_editrc_cancelDistProcess_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_editrc_distProcess_dialog.cpp -o obj/Release/rcbasic_editrc_distProcess_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_editrc_distribute_dialog.cpp -o obj/Release/rcbasic_editrc_distribute_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c rcbasic_editrc_genKey_dialog.cpp -o obj/Release/rcbasic_editrc_genKey_dialog.o
g++ -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -O2  -c tools_menu.cpp -o obj/Release/tools_menu.o
g++  -o bin/Release/rcbasic_edit obj/Release/build_menu.o obj/Release/help_menu.o obj/Release/parserThread.o obj/Release/projects.o obj/Release/rc_closeFileSavePrompt_dialog.o obj/Release/rc_closeProjectSavePrompt_dialog.o obj/Release/rc_debugger_dialog.o obj/Release/rc_find_dialog.o obj/Release/rc_ideApp.o obj/Release/rc_newFile_dialog.o obj/Release/rcbasic_edit.o obj/Release/rcbasic_edit_fileProperties_dialog.o obj/Release/rcbasic_edit_frame.o obj/Release/rcbasic_edit_gotoLine_dialog.o obj/Release/rcbasic_edit_newProject_dialog.o obj/Release/rcbasic_edit_preference_dialog.o obj/Release/rcbasic_edit_projectEnvironment_dialog.o obj/Release/rcbasic_edit_projectSettings_dialog.o obj/Release/rcbasic_edit_projectVariableEdit_dialog.o obj/Release/rcbasic_edit_replace_dialog.o obj/Release/rcbasic_edit_searchWrap_dialog.o obj/Release/rcbasic_edit_setColorScheme_dialog.o obj/Release/rcbasic_editrc_cancelDistProcess_dialog.o obj/Release/rcbasic_editrc_distProcess_dialog.o obj/Release/rcbasic_editrc_distribute_dialog.o obj/Release/rcbasic_editrc_genKey_dialog.o obj/Release/tools_menu.o  -s -L/usr/lib/x86_64-linux-gnu -pthread   -lwx_gtk3u_stc-3.0 -lwx_gtk3u_aui-3.0 -lwx_gtk3u_richtext-3.0 -lwx_gtk3u_xrc-3.0 -lwx_gtk3u_webview-3.0 -lwx_gtk3u_html-3.0 -lwx_gtk3u_qa-3.0 -lwx_gtk3u_adv-3.0 -lwx_gtk3u_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0  -Wl,--allow-multiple-definition  
