#ifndef __rcbasic_editrc_closeFileSavePrompt_dialog__
#define __rcbasic_editrc_closeFileSavePrompt_dialog__

/**
@file
Subclass of rc_closeFileSavePrompt_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

#define fileCloseFlag_CANCEL 0
#define fileCloseFlag_DONT_SAVE 1
#define fileCloseFlag_SAVE 2


/** Implementing rc_closeFileSavePrompt_dialog */
class rcbasic_edit_closeFileSavePrompt_dialog : public rc_closeFileSavePrompt_dialog
{
    private:
        int fileCloseFlag;
	protected:
		// Handlers for rc_closeFileSavePrompt_dialog events.
		void onCloseFileSaveCancel( wxCommandEvent& event );
		void onCloseFileSaveDontSave( wxCommandEvent& event );
		void onCloseFileSaveOk( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_edit_closeFileSavePrompt_dialog( wxWindow* parent, const wxString& title );
		int getFileCloseFlag();
	//// end generated class members

};

#endif // __rcbasic_editrc_closeFileSavePrompt_dialog__
