#ifndef __rcbasic_editrc_find_dialog__
#define __rcbasic_editrc_find_dialog__

/**
@file
Subclass of rc_find_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"
#include "rcbasic_edit_frame.h"
#include "projects.h"

//// end generated include

#define find_dialog_value_MARK 2
#define find_dialog_value_INPROJECT 3
#define find_dialog_value_INFILE 4
#define find_dialog_value_CLOSE 5

/** Implementing rc_find_dialog */
class rcbasic_edit_find_dialog : public rc_find_dialog
{
    private:
        int find_dialog_value;
        rcbasic_project* current_project;
        rcbasic_edit_frame* frame;
        rcbasic_edit_txtCtrl* current_file;
        //vector<uint64_t> search_line_number;

    protected:
		// Handlers for rc_find_dialog events.
		void onMarkButtonClick( wxCommandEvent& event );
		void onInProjectButtonClick( wxCommandEvent& event );
		void onInFileButtonClick( wxCommandEvent& event );
		void onCloseButtonClick( wxCommandEvent& event );
		void onPreviousButtonClick( wxCommandEvent& event );
		void onNextButtonClick( wxCommandEvent& event );

	public:
		/** Constructor */
		rcbasic_edit_find_dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __rcbasic_editrc_find_dialog__
