#ifndef __rcbasic_editrc_newFile_dialog__
#define __rcbasic_editrc_newFile_dialog__

/**
@file
Subclass of rc_newFile_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

#define newFileFlag_CANCEL 0
#define newFileFlag_OK 1

/** Implementing rc_newFile_dialog */
class rcbasic_edit_newFile_dialog : public rc_newFile_dialog
{
    private:
        int newFileFlag;
	protected:
		// Handlers for rc_newFile_dialog events.
		void onCreateNewSourceCancel( wxCommandEvent& event );
		void onCreateNewSourceOk( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_edit_newFile_dialog( wxWindow* parent );
		int getNewFileFlag();
	//// end generated class members

};

#endif // __rcbasic_editrc_newFile_dialog__
