#ifndef __rcbasic_editrc_setColorScheme_dialog__
#define __rcbasic_editrc_setColorScheme_dialog__

/**
@file
Subclass of rc_setColorScheme_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"
#include "rcbasic_edit_frame.h"

//// end generated include

/** Implementing rc_setColorScheme_dialog */
class rcbasic_edit_setColorScheme_dialog : public rc_setColorScheme_dialog
{
    private:
        rcbasic_edit_frame* p_frame;
        vector<rcbasic_edit_txtCtrl*> openFiles;

        wxFileName scheme_path;

	protected:
		// Handlers for rc_setColorScheme_dialog events.
		void onSchemeSelected( wxCommandEvent& event );
		void onSchemeCloseButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_edit_setColorScheme_dialog( wxWindow* parent );
	//// end generated class members




};

#endif // __rcbasic_editrc_setColorScheme_dialog__
