#ifndef __rcbasic_editrc_projectSettings_dialog__
#define __rcbasic_editrc_projectSettings_dialog__

/**
@file
Subclass of rc_projectSettings_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_projectSettings_dialog */
class rcbasic_editrc_projectSettings_dialog : public rc_projectSettings_dialog
{
	protected:
		// Handlers for rc_projectSettings_dialog events.
		void onMainSourceListBoxSelection( wxCommandEvent& event );
		void onFileSelection( wxCommandEvent& event );
		void onFileDoubleClick( wxCommandEvent& event );
		void onAddFilesButtonClick( wxCommandEvent& event );
		void onRemoveSelectedButtonClick( wxCommandEvent& event );
		void onFilePropertiesButtonClick( wxCommandEvent& event );
		void onCancelButtonClick( wxCommandEvent& event );
		void onOKButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_editrc_projectSettings_dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __rcbasic_editrc_projectSettings_dialog__
