#ifndef __rcbasic_editrc_replace_dialog__
#define __rcbasic_editrc_replace_dialog__

/**
@file
Subclass of rc_replace_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"
#include "rcbasic_edit_frame.h"
#include "projects.h"

//// end generated include

#define replace_dialog_INFILE 1
#define replace_dialog_INPROJECT 2
#define replace_dialog_INSELECTION 3

/** Implementing rc_replace_dialog */
class rcbasic_edit_replace_dialog : public rc_replace_dialog
{
    private:
        int replace_dialog_value;
        rcbasic_project* current_project;
        rcbasic_edit_frame* parent_frame;
        rcbasic_edit_txtCtrl* current_file;
        int start_pos;
        int current_search_pos;
        wxString search_term;

	protected:
		// Handlers for rc_replace_dialog events.
		void onReplaceInProjectClick( wxCommandEvent& event );
		void onReplaceInFileClick( wxCommandEvent& event );
		void onReplaceInSelectionClick( wxCommandEvent& event );
		void onFindNextClick( wxCommandEvent& event );
		void onReplaceClick( wxCommandEvent& event );
		void onReplaceCloseClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_edit_replace_dialog( wxWindow* parent );
		int getValue();
		wxString getSearchText();
		wxString getReplaceText();
		int getFlags();

        void replaceInFile(rcbasic_edit_txtCtrl* txtCtrl_obj, wxString search_txt, wxString replace_txt, int flag);
        void replaceInSelection(rcbasic_edit_txtCtrl* txtCtrl_obj, wxString search_txt, wxString replace_txt, int flag);
	//// end generated class members

};

#endif // __rcbasic_editrc_replace_dialog__
