#ifndef __rcbasic_editrc_setColorScheme_dialog__
#define __rcbasic_editrc_setColorScheme_dialog__

/**
@file
Subclass of rc_setColorScheme_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_setColorScheme_dialog */
class rcbasic_editrc_setColorScheme_dialog : public rc_setColorScheme_dialog
{
	public:
		/** Constructor */
		rcbasic_editrc_setColorScheme_dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __rcbasic_editrc_setColorScheme_dialog__
