#ifndef __rcbasic_editrc_ideFrame__
#define __rcbasic_editrc_ideFrame__

/**
@file
Subclass of rc_ideFrame, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_ideFrame */
class rcbasic_editrc_ideFrame : public rc_ideFrame
{
	protected:
		// Handlers for rc_ideFrame events.
		void toggleToolbar( wxCommandEvent& event );
		void toggleSideBar( wxCommandEvent& event );
		void toggleMessageWindow( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_editrc_ideFrame( wxWindow* parent );
	//// end generated class members


};

#endif // __rcbasic_editrc_ideFrame__
