#ifndef __rcbasic_editrc_projectSettings_dialog__
#define __rcbasic_editrc_projectSettings_dialog__

/**
@file
Subclass of rc_projectSettings_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"
#include "rcbasic_edit_frame.h"

//// end generated include

#define PROJECT_SETTINGS_CANCEL 0
#define PROJECT_SETTINGS_OK 1

/** Implementing rc_projectSettings_dialog */
class rcbasic_edit_projectSettings_dialog : public rc_projectSettings_dialog
{
    private:
        rcbasic_edit_frame* parent_frame;
        rcbasic_project* new_project;
        rcbasic_project* current_project;
        int projectSettings_flag;
	protected:
		// Handlers for rc_projectSettings_dialog events.
		void onMainSourceListBoxSelection( wxCommandEvent& event );
		void onFileSelection( wxCommandEvent& event );
		void onFileDoubleClick( wxCommandEvent& event );
		void onAddFilesButtonClick( wxCommandEvent& event );
		void onRemoveSelectedButtonClick( wxCommandEvent& event );
		void onFilePropertiesButtonClick( wxCommandEvent& event );
		void onCancelButtonClick( wxCommandEvent& event );
		void onOKButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_edit_projectSettings_dialog( wxWindow* parent );
		void openProperties();
		rcbasic_project* getNewProject() { return new_project; }
		int getFlag() { return projectSettings_flag; }
	//// end generated class members

};

#endif // __rcbasic_editrc_projectSettings_dialog__
