#ifndef __rcbasic_editrc_fileProperties_dialog__
#define __rcbasic_editrc_fileProperties_dialog__

/**
@file
Subclass of rc_fileProperties_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_fileProperties_dialog */
class rcbasic_editrc_fileProperties_dialog : public rc_fileProperties_dialog
{
	protected:
		// Handlers for rc_fileProperties_dialog events.
		void onCancelButtonClick( wxCommandEvent& event );
		void onOKButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_editrc_fileProperties_dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __rcbasic_editrc_fileProperties_dialog__
