#ifndef __rcbasic_editrc_ideFrame__
#define __rcbasic_editrc_ideFrame__

/**
@file
Subclass of rc_ideFrame, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"
#include "projects.h"
#include <wx/imaglist.h>
#include <vector>

//// end generated include

/** Implementing rc_ideFrame */
class rcbasic_edit_frame : public rc_ideFrame
{
    private:
        bool toolbarVisible;
        bool sideBarVisible;
        bool messageWindowVisible;
        std::vector<rcbasic_project*> open_projects;
        rcbasic_project* context_project;
        wxImageList* project_tree_imageList;
        int project_tree_rootImage;
        int project_tree_folderImage;
        int project_tree_fileImage;
	protected:
		// Handlers for rc_ideFrame events.
		void createNewProject( wxCommandEvent& event );
		void toggleToolbar( wxCommandEvent& event );
		void toggleSideBar( wxCommandEvent& event );
		void toggleMessageWindow( wxCommandEvent& event );
		void onProjectTreeContextMenu( wxTreeEvent& event );
		void onTreeContextClick( wxCommandEvent &evt );
		void onProjectTreeNodeActivated( wxTreeEvent& event );
	public:
		/** Constructor */
		rcbasic_edit_frame( wxWindow* parent );
		int getProjectFromRoot(wxTreeItemId node);
		void updateProjectTree(int project_index);
		void addFileToProject(wxFileName sourceFile);
		void projectTreeContextMenu();
		wxFileName openFileDialog();
	//// end generated class members


};

#endif // __rcbasic_editrc_ideFrame__
