#ifndef __rcbasic_editrc_find_dialog__
#define __rcbasic_editrc_find_dialog__

/**
@file
Subclass of rc_find_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_find_dialog */
class rcbasic_editrc_find_dialog : public rc_find_dialog
{
	protected:
		// Handlers for rc_find_dialog events.
		void onMarkButtonClick( wxCommandEvent& event );
		void onInProjectButtonClick( wxCommandEvent& event );
		void onInFileButtonClick( wxCommandEvent& event );
		void onCloseButtonClick( wxCommandEvent& event );
		void onPreviousButtonClick( wxCommandEvent& event );
		void onNextButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_editrc_find_dialog( wxWindow* parent );
	//// end generated class members


};

#endif // __rcbasic_editrc_find_dialog__
