#ifndef __rcbasic_editrc_searchWrap_dialog__
#define __rcbasic_editrc_searchWrap_dialog__

/**
@file
Subclass of rc_searchWrap_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

#define searchWrap_value_CANCEL 0
#define searchWrap_value_OK 1

/** Implementing rc_searchWrap_dialog */
class rcbasic_edit_searchWrap_dialog : public rc_searchWrap_dialog
{
    private:
        int searchWrap_value;
	protected:
		// Handlers for rc_searchWrap_dialog events.
		void onSearchWrapCancel( wxCommandEvent& event );
		void onSearchWrapOk( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_edit_searchWrap_dialog( wxWindow* parent, wxString search_term );
		int getValue();
	//// end generated class members

};

#endif // __rcbasic_editrc_searchWrap_dialog__
