#ifndef __rcbasic_editrc_cancelDistProcess_dialog__
#define __rcbasic_editrc_cancelDistProcess_dialog__

/**
@file
Subclass of rc_cancelDistProcess_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_cancelDistProcess_dialog */
class rcbasic_editrc_cancelDistProcess_dialog : public rc_cancelDistProcess_dialog
{
	protected:
		// Handlers for rc_cancelDistProcess_dialog events.
		void onYesButtonClick( wxCommandEvent& event );
		void onNoButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_editrc_cancelDistProcess_dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __rcbasic_editrc_cancelDistProcess_dialog__
