#ifndef __rcbasic_editrc_replace_dialog__
#define __rcbasic_editrc_replace_dialog__

/**
@file
Subclass of rc_replace_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_replace_dialog */
class rcbasic_editrc_replace_dialog : public rc_replace_dialog
{
	protected:
		// Handlers for rc_replace_dialog events.
		void onReplaceInProjectClick( wxCommandEvent& event );
		void onReplaceInFileClick( wxCommandEvent& event );
		void onReplaceInSelectionClick( wxCommandEvent& event );
		void onFindNextClick( wxCommandEvent& event );
		void onReplaceClick( wxCommandEvent& event );
		void onReplaceCloseClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_editrc_replace_dialog( wxWindow* parent );
	//// end generated class members


};

#endif // __rcbasic_editrc_replace_dialog__
