#ifndef __rcbasic_editrc_debugger__
#define __rcbasic_editrc_debugger__

/**
@file
Subclass of rc_debugger, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_debugger */
class rcbasic_editrc_debugger : public rc_debugger
{
	protected:
		// Handlers for rc_debugger events.
		void onPause( wxCommandEvent& event );
		void onStep( wxCommandEvent& event );
		void onRun( wxCommandEvent& event );
		void onEnd( wxCommandEvent& event );
		void onClose( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_editrc_debugger( wxWindow* parent );
	//// end generated class members


};

#endif // __rcbasic_editrc_debugger__
