#ifndef __rcbasic_editrc_projectEnvironment_dialog__
#define __rcbasic_editrc_projectEnvironment_dialog__

/**
@file
Subclass of rc_projectEnvironment_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"
#include "projects.h"
#include <vector>
//// end generated include

#define PROJECT_ENVIRONMENT_DLG_CANCEL 0
#define PROJECT_ENVIRONMENT_DLG_OK 1

/** Implementing rc_projectEnvironment_dialog */
class rcbasic_edit_projectEnvironment_dialog : public rc_projectEnvironment_dialog
{
    private:
        int projectEnv_flag;
        std::vector<rcbasic_edit_env_var> env_vars;

	protected:
		// Handlers for rc_projectEnvironment_dialog events.
		void onClearAllButtonClick( wxCommandEvent& event );
		void onRemoveSelectedButtonClick( wxCommandEvent& event );
		void onAddVariableButtonClick( wxCommandEvent& event );
		void onCancelButtonClick( wxCommandEvent& event );
		void onOKButtonClick( wxCommandEvent& event );
		void onEditVariableButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_edit_projectEnvironment_dialog( wxWindow* parent, std::vector<rcbasic_edit_env_var> vars );
	//// end generated class members
        std::vector<rcbasic_edit_env_var> getVars();
        int getFlag();
};

#endif // __rcbasic_editrc_projectEnvironment_dialog__
