#ifndef __rcbasic_editrc_projectEnvironment_dialog__
#define __rcbasic_editrc_projectEnvironment_dialog__

/**
@file
Subclass of rc_projectEnvironment_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_projectEnvironment_dialog */
class rcbasic_editrc_projectEnvironment_dialog : public rc_projectEnvironment_dialog
{
	protected:
		// Handlers for rc_projectEnvironment_dialog events.
		void onClearAllButtonClick( wxCommandEvent& event );
		void onRemoveSelectedButtonClick( wxCommandEvent& event );
		void onAddVariableButtonClick( wxCommandEvent& event );
		void onCancelButtonClick( wxCommandEvent& event );
		void onOKButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_editrc_projectEnvironment_dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __rcbasic_editrc_projectEnvironment_dialog__
