#ifndef __rcbasic_editrc_genKey_dialog__
#define __rcbasic_editrc_genKey_dialog__

/**
@file
Subclass of rc_genKey_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_genKey_dialog */
class rcbasic_editrc_genKey_dialog : public rc_genKey_dialog
{
	protected:
		// Handlers for rc_genKey_dialog events.
		void onOKButtonClick( wxCommandEvent& event );
		void onCancelButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_editrc_genKey_dialog( wxWindow* parent );
	//// end generated class members



};

#endif // __rcbasic_editrc_genKey_dialog__
